language: go
jobs:
  include:
    - go: 1.15
os: linux
dist: xenial
env:
  - TURBO_VER="1.5.1" CGO_LDFLAGS="-L/tmp/libjpeg-turbo/lib64" CGO_CPPFLAGS="-I/tmp/libjpeg-turbo/include" LD_LIBRARY_PATH="/tmp/libjpeg-turbo/lib64"
before_install:
  - ./travis-install-libjpeg-turbo.sh "$TURBO_VER"
  - cd $HOME/gopath/src/github.com/c3sr/go-libjpeg
install:
  - go build -tags=nogpu ./...
script: true
after_script:
  - go test -tags=nogpu -race -v -cover ./...
