language: go

go:
  - 1.10.x
  - tip

env:
  - TURBO_VER=""
  - TURBO_VER="1.5.1" CGO_LDFLAGS="-L/tmp/libjpeg-turbo/lib64" CGO_CPPFLAGS="-I/tmp/libjpeg-turbo/include" LD_LIBRARY_PATH="/tmp/libjpeg-turbo/lib64"

before_install:
  - ./travis-install-libjpeg-turbo.sh "$TURBO_VER"
  - cd $HOME/gopath/src/github.com/rai-project/go-libjpeg
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
install:
- dep ensure -v
- rm -fr vendor/github.com/Sirupsen
- find vendor -type f -exec sed -i 's/Sirupsen/sirupsen/g' {} +
- go build
script:
  - go test -a -test.v ./...
  - cd jpeg && go test -a -bench . -benchtime 10s
